### ISSUE TITLE
Support loading a template from a file, when run on the server

### ISSUE THREAD

**Issue by alexschneider** [valotas/mustache4dart#31]
It's kind of annoying to have to write the boilerplate code:

``` dart
Future<String> mustache(String filename, Object context) {
  return (new File('$templateDirectory/$filename')).readAsString()
      .then((String document) {

        String partialProvider(String partialName) =>
            (new File('$templateDirectory/$partialName')).readAsStringSync();

        return mustache4dart.render(document, context, partial: partialProvider);
  });
}
```

I probably should be caching, because file I/O operations are expensive. 

every time I want to load templates from a directory. Is it possible to have a method, say, `renderFromDirectory('$templateDirectory', '$templateName');`, ideally with built in error handling that would handle partials and caching for me?

**Comment by snnn** [comment]
Is it possible to replace readAsStringSync() with readAsString()  in partialProvider? 
As it is a webserver(not a command line app), it should not do any sync IO in its request handler.
