### ISSUE TITLE
Does not find names in super classes

### ISSUE THREAD

**Issue by sethladd** [valotas/mustache4dart#33]
Consider this case:

```
class A {
  String get foo => 'foo';
}

class B extends A {
}
```

and inside the template:

`{{ b.foo }}`

Expected: 'foo' to be printed

Actual: nothing is printed

If I move the getter down into B, then it works.

**Comment by valotas** [comment]
This is a bug. I'll have a look at it during the weekend. Thanks for reporting it.

**Comment by sethladd** [comment]
Proposed fix here: https://github.com/valotas/mustache4dart/pull/34

**Comment by valotas** [comment]
Thanks a lot for the PR. That was fast :)
