### ISSUE TITLE
Suggest switching to travis ci to get testing of PRs

### ISSUE THREAD

**Issue by sethladd** [valotas/mustache4dart#35]
Travis CI lets you test incoming Pull Requests, which is pretty sweet.

Also, there is now native support for a Dart runtime inside of Travis: http://blog.travis-ci.com/2015-01-28-introducing-new-community-supported-language-dart/

**Comment by valotas** [comment]
Will do that

**Comment by valotas** [comment]
Done that!

**Comment by sethladd** [comment]
:)
