### ISSUE TITLE
How to error on incorrect tag?

### ISSUE THREAD

**Issue by sethladd** [valotas/mustache4dart#36]
Hi,

Is there a way to throw an exception this library encounters an unknown/misspelled tag?

I would be nice to have an option like "errorOnUnknownTags" :)

Thanks!

**Comment by valotas** [comment]
Hi @sethladd do yo mean to inform you somehow that a property has not been found with in the given context? It should be straight forward to implement. I'll have something by the end of the day

**Comment by sethladd** [comment]
Yes, an option to throw an exception when a property or tag is not found in the current context. Bonus points for telling me the file name, line number, and character position where the missing tag/prop was found.

**Comment by valotas** [comment]
Created #38 for the bonus implementation
