### ISSUE TITLE
Unable to call .length on a List

### ISSUE THREAD

**Issue by sethladd** [valotas/mustache4dart#44]
Hi,

I'm trying to do this:

Data model:

```
class Foo {
  List<String> things = ['one', 'two'];
}
```

Template:

```
{{#foo.things.length}}
{{#foo.things}}
<ul>
  <li>{{}}</li>
</ul>
{{/foo.things}}
{{/foo.things.length}}
```

In other words, I'd like to check the length of a list to see if there's anything there, so I can render `<ul>`

The exception is:

```
Unhandled exception:
Closure call with mismatched arguments: function '_getMustachContext'

NoSuchMethodError: method not found: '_getMustachContext'
Receiver: Instance of '_IterableMustacheContextDecorator'
Arguments: ["length"]
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#1      _MustacheContext._getContextForKey (package:mustache4dart/mustache_context.dart:75:37)
#2      _MustacheContext._getInThisOrParent (package:mustache4dart/mustache_context.dart:56:35)
```

Perhaps IterableMustacheContextDectorator is just dealing with iterables and not lists ?

**Comment by sethladd** [comment]
Thanks for taking a look!

**Comment by valotas** [comment]
From the [mustache specs](https://github.com/mustache/spec/blob/master/specs/sections.yml):

```
  - name: Empty List
    desc: Empty lists should behave like falsey values.
    data: { list: [ ] }
    template: '"{{#list}}Yay lists!{{/list}}"'
    expected: '""'
```

That said, the following should be sufficient:

```
{{#foo.things}}
<ul>
  <li>{{}}</li>
</ul>
{{/foo.things}}
```

**Comment by valotas** [comment]
Is the codebase you are working on open? Maybe I can have a look at the mustache part.

**Comment by sethladd** [comment]
I'll try that, thanks. I thought `<ul>` would be repeated for each element in `things` ?

Our new dartdoc uses mustache4dart: https://github.com/dart-lang/dartdoc

**Comment by valotas** [comment]
Yes you are right. But your code does the same too. I'll have a closer look tomorrow.

**Comment by sethladd** [comment]
The spec says what to do when you encounter an empty list: "do nothing" aka "kinda falsey". However, the inverse is not true. A non-empty list isn't truthy, it's for iteration.

Thanks for taking a look!

**Comment by sethladd** [comment]
Hi! Can we reopen this issue? It's marked as "wontfix".

Thanks!

**Comment by valotas** [comment]
I had a look at it. with 1.0.10 you should be able to do

```
{{^list.empty}}
<ul>
{{#list}}<li>{{.}}</li>{{/list}}
</ul>
{{/list.empty}}
```

I would like to avoid using the `length`. Is there any particular reason for using it?

**Comment by sethladd** [comment]
Thanks! Can you push to pub? I'd love to start using this.

**Comment by valotas** [comment]
It looks like this got off my radar. I'll publish a new version today night.

**Comment by sethladd** [comment]
Thank you!
