### ISSUE TITLE
compile doesn't return a type annotation

### ISSUE THREAD

**Issue by sethladd** [valotas/mustache4dart#50]
It would be really helpful if `compile` returned a type annotation. Right now, it doesn't use any type annotation.

I'm refactoring my code that uses mustache4dart and the refactoring is a bit challenging because the analyzer doesn't know what compile() is returning.

Since `compile` returns a _Template, I suspect we need a public typedef for "things that can render a template"

Thanks!

**Comment by sethladd** [comment]
Addressed by https://github.com/valotas/mustache4dart/pull/51

**Comment by sethladd** [comment]
Sorry for including a README formatting change in here. I also forgot to update the CHANGELOG

**Comment by valotas** [comment]
Merged #51

**Comment by sethladd** [comment]
Thanks!
