### ISSUE TITLE
Is it possible to get the AST/tokens from a template?

### ISSUE THREAD

**Issue by kulshekhar** [valotas/mustache4dart#53]
Is it possible to use this package to fetch the AST or tokens of a mustache template?

**Comment by valotas** [comment]
Not really. What are you trying to do?

**Comment by kulshekhar** [comment]
I'm trying to integrate Mustache with IncrementalDOM to enable efficient updates of the DOM. I'm currently using the javascript mustache processor to parse the template into tokens and would prefer an all dart solution

**Comment by valotas** [comment]
Where, there is an internal ast kinda thing but never had in mind to expose this. Feel free to experiment thought.

**Comment by EasonPai** [comment]
I would like to get tokens before rendering too.

What I want is to make sure if any token cannot be rendered with context, 
then I can put a default value for it before it is rendered.
