### ISSUE TITLE
strong mode compliancy

### ISSUE THREAD

**Issue by sircco** [valotas/mustache4dart#61]
found this while trying to use dartdevc

[error] The return type 'String' isn't a 'void', as defined by the method '_write'. (package:mustache4dart/src/tmpl.dart, line 91, col 14)
[error] The return type 'String' isn't a 'StringBuffer', as defined by the method 'apply'. (package:mustache4dart/src/tokens.dart, line 86, col 21)
[error] The return type 'String' isn't a 'StringBuffer', as defined by the method 'apply'. (package:mustache4dart/src/tokens.dart, line 100, col 14)
[error] The return type 'String' isn't a 'StringBuffer', as defined by the method 'apply'. (package:mustache4dart/src/tokens.dart, line 107, col 14)
[error] The return type 'String' isn't a 'StringBuffer', as defined by the method 'apply'. (package:mustache4dart/src/tokens.dart, line 169, col 14)
[error] The return type 'String' isn't a 'StringBuffer', as defined by the method 'apply'. (package:mustache4dart/src/tokens.dart, line 186, col 7)
[error] The return type 'String' isn't a 'StringBuffer', as defined by the method 'apply'. (package:mustache4dart/src/tokens.dart, line 208, col 12)
[error] The return type 'String' isn't a 'StringBuffer', as defined by the method 'apply'. (package:mustache4dart/src/tokens.dart, line 232, col 7)
[error] The method 'replaceAll' isn't defined for the class 'StringBuffer'. (package:mustache4dart/src/tokens.dart, line 248, col 10)
[error] The return type 'String' isn't a 'StringBuffer', as defined by the method 'apply'. (package:mustache4dart/src/tokens.dart, line 275, col 14)
[error] The method 'forEach' isn't defined for the class 'MustacheContext'. (package:mustache4dart/src/tokens.dart, line 279, col 11)
[error] The return type 'String' isn't a 'StringBuffer', as defined by the method 'apply'. (package:mustache4dart/src/tokens.dart, line 319, col 7)
[error] The return type 'String' isn't a 'StringBuffer', as defined by the method 'apply'. (package:mustache4dart/src/tokens.dart, line 335, col 14)
[error] The return type 'String' isn't a 'StringBuffer', as defined by the method 'apply'. (package:mustache4dart/src/tokens.dart, line 338, col 12)

**Comment by valotas** [comment]
It looks like a bug. I'll have a look at it
