### ISSUE TITLE
Any plans using reflectable or one of the code_gen techniques to get rid of mirrors?

### ISSUE THREAD

**Issue by MikeMitterer** [valotas/mustache4dart#66]

**Comment by valotas** [comment]
How would that help?

**Comment by MikeMitterer** [comment]
Dart has no clear strategy with reflections. There are "mirrors" and on the other hand there is the reflectable-package. reflectable runs on server, web and flutter and it gets more love from Google. I have the feeling (not tested) that reflectable compiles faster than mirrors if you use dartdevc.

I'd love to switch my mdl-package to reflectable but I need a mustache-package that has support for it.

**Comment by valotas** [comment]
I think it is time to give this a try :) I think I can create something the following days

**Comment by MikeMitterer** [comment]
Cool! If you go for reflectable - I think it's almost there: https://github.com/dart-lang/reflectable/issues/98

**Comment by valotas** [comment]
valotas/mustache4dart/pull/67 is a first attempt.

**Comment by valotas** [comment]
#81 is addressing this issue. Closing this as a duplicate to #73
